### ISSUE TITLE
taxonomicConceptLabel value wrong

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#102]
@gsautter in this case https://zenodo.org/record/6372282#.YjhZNnrML8A  the [openbiodiv:TaxonomicConceptLabel 
Bazboltonia microps &, 2022 sec. Camacho & Feitosa, 2022](http://openbiodiv.net/ontology#TaxonomicConceptLabel)openbiodiv:TaxonomicConceptLabel 
[Bazboltonia microps &, 2022 sec. Camacho & Feitosa, 2022](https://zenodo.org/search?custom=%5Bopenbiodiv%3ATaxonomicConceptLabel%5D%3A%5BBazboltonia+microps+%26%2C+2022+sec.+Camacho+%26+Feitosa%2C+2022%5D) is wrong.

should be Bazboltonia microps (Borgmeier 1957) sec. Camacho & Feitosa, 2022

**Comment by gsautter** [comment]
Looks as though this a basically a problem with "comb. nov.", "stat. nov.", and "nom. nov." only, as those are the only cases where we have a nomenclatorial act that does involve a basionym authority to cite ... might have slipped through the cracks on testing ... digging in.

**Comment by gsautter** [comment]
Fixed.
