### ISSUE TITLE
images scrambled

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#32]
https://zenodo.org/record/288986
BD4DFFA8FF83FFF24C1EFFD0E01EDE56

https://zenodo.org/record/285502
article FFD44A36FFDA870DAA5F7117FF98C036

https://zenodo.org/record/286484
FF80087FFFF1FFDD41474F21FFE8FFB9

**Comment by gsautter** [comment]
Article `BD4DFFA8FF83FFF24C1EFFD0E01EDE56` (https://zenodo.org/record/288983) is fine now, including the links, i.e., all the figures are intact.

Article `FFD44A36FFDA870DAA5F7117FF98C036` (https://zenodo.org/record/285499) I just repaired, should be fine soon as the Zenodo up-sync is through ... and it is, with links to the intact figures now.

Article `FF80087FFFF1FFDD41474F21FFE8FFB9` (https://zenodo.org/record/286482) is fine now, including the links, i.e., all the figures are intact.
