### ISSUE TITLE
upload of file from GGI that previously has been in TB from GG

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#48]
this is the original file 
http://tb.plazi.org/GgServer/summary/4F0C597EE449C418A221140B4A156407
https://zenodo.org/record/27080#.XNLiGOgzbAS

I now downloaded the file from Zenodo, run it through ABBYY, GGI and uploaded it, adding the Zenodo upload number.

What is happening now? It is is on TB  with name jNatHist.28_ocr.pdf

This is a more general case. We have a whole series of ant deposits on Zenodo and TB that we run though GG, but they all do not have figures, etc. So what needs to be done to bring them up to speed?

Also, these files are different on GBIF. https://www.gbif.org/species/1319640 ., but this might be because there are no figures. need to be checked.

**Comment by gsautter** [comment]
After the PDF upload, it got a new UUID based upon the hash of the PDF, just like all other IMFs. The UUID of the IMF based document is `FF98FFE4FFD2FFB1CE7990186062FFED`. The figures are on Zenodo, linked and everything, just looks like the treatment doesn't have any `figureCitation`s.

**Comment by gsautter** [comment]
I added the `figureCitation`s now, had been missed due to OCR issues.

**Comment by gsautter** [comment]
The treatment is at http://tb.plazi.org/GgServer/html/03A1879CFFD3FFB4CD75987266B6FD85
