### ISSUE TITLE
Include the license in the document metadata

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#50]
we should extract the licence from the article in the GGI process, that is make this part of the document metadata. This is increasingly important since the emphasis in the open data movement focuses on this element.

**Comment by lyubomirpenev** [comment]
I believe we have the license in our XMLs. I wonder @gsautter and @teodorgeorgiev if you do harvest these?

**Comment by gsautter** [comment]
Just one question here (I'm in the process implementing this): Should there be a license selector only for the article proper and for the figures, or for the treatments as well? We might need it at some point ...

**Comment by gsautter** [comment]
Another question yet is whether or not we should include functionality for selecting a dedicated license _per individual figure_ (would most likely be stored as an attribute of the caption)? There might be use cases ...

**Comment by gsautter** [comment]
Deployed on server side, with a wide range of flexibility. The license handling plug-in for GGI comes with the next update (would be good to get an answer to my last question in https://github.com/plazi/Biodiversity-Literature-Repository/issues/49 beforehand).
