### ISSUE TITLE
change licences for EJT images in BLR to "CC BY"

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#51]
We should change all the licenses in BLR for the "European Journal of Taxonomy" from "licence not specified" to "CC BY"

The same should be for all the articles that are "CC BY".

See also https://github.com/plazi/Biodiversity-Literature-Repository/issues/49

**Comment by gsautter** [comment]
Implemented and deployed, update is underway, should be done in a few hours.
