### ISSUE TITLE
figure wrong decoded FFB4FFE3246FFF85FFC8FFAE7B5AFFDC 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#53]
![image](https://user-images.githubusercontent.com/4609956/61577215-8b6db900-aae4-11e9-85d4-1116636baf5e.png)

in Zenodo

![image](https://user-images.githubusercontent.com/4609956/61577223-a17b7980-aae4-11e9-82bb-50f4ec9e2a25.png)

**Comment by gsautter** [comment]
Could you release the lock on this one? I'd like to take a look at it.

**Comment by myrmoteras** [comment]
I still have 30 mc to correct. So probably tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by myrmoteras** [comment]
It is released now

**Comment by gsautter** [comment]
This is a weird one ... the GGI page image comes up with the correct figure, faithful to the PDF, but the supplement PNG is inverted ... will check.

**Comment by gsautter** [comment]
Just re-decoded the PDF, and both the figures in the page images and the supplementary PNGs come up correctly ...

**Comment by gsautter** [comment]
Repaired the figures now, and had them placed in new depositions the IMF now links to. However, I could not reproduce the error and thus wasn't able to implement any corrective measures ... let's see if this repeats.

**Comment by myrmoteras** [comment]
this seems to be old parscing anyway

**Comment by gsautter** [comment]
Yes ... can you determine when this PDF was originally converted? I.e., the create time of the original IMF?

**Comment by myrmoteras** [comment]
it is your system - you should be able to know the V1 has been uploaded...

**Comment by gsautter** [comment]
"uploaded" for sure ... that's the creation time in the stats. How long the IMF sat on your machine before you uploaded it is a different question altogether, though. I'm asking exactly because this is the re-emergence of an error I fixed a good while ago ...

**Comment by myrmoteras** [comment]
a couple of hours at best. I don't keep anything on my machine after processing. I thought you fixed this too. But the first upload to TB is anyway the moment when the article has been converted.

**Comment by gsautter** [comment]
Maybe your batch command accidentally pointed to an older installation?

**Comment by myrmoteras** [comment]
again. I did NOT batch process. I just opened the file to parse the MC

**Comment by gsautter** [comment]
Ah, OK, now I got it ... sorry for the misunderstanding. The IMF was first uploaded April 4, 2016 ... yes, that was before the fix.
