### ISSUE TITLE
figures not linked from the publication metadata

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#58]
In this case, https://zenodo.org/record/3490215#.XaV7i0YzbAT the captions of the figures are on top, and thus GG did not discover and link them.

When I did this manually and restored the file to TB, all the images showed up on BLR, but the links to the images have not been embedded in the article metdata. See eg https://zenodo.org/record/3490274#.XaV8MEYzbAR

**Comment by gsautter** [comment]
This is by and large a template problem ... in all Zootaxa articles we've seen before this one, the captions are below the figures, so the template specifies that arrangement, restricting where the responsible GGI gizmo looks for figure captions. Easy to remove the restriction, but that would incur an increased risk of errors in other places, exactly what the templates are intended to prevent.

Using "Assign Caption" on the figures is an easy way of fixing this for the document at hand, but if such cases keep coming, we can surely modify the template accordingly.

**Comment by gsautter** [comment]
Embedding the links takes a little after you release the document ... first of all, the figure deposition numbers (and derived lins and DOIs) have to be written back to the IMF, which the server only can do after you release the document by closing it in GGI, and then the Zenodo uploader updates the article metadata ... if you look now, the figures are linked: https://zenodo.org/record/3490215

**Comment by myrmoteras** [comment]
super - it was just much longer than what I am used to. But it is fine now and I will be more patient later - and also forget it...

**Comment by myrmoteras** [comment]
the upload is now much faster, and this is very convenient and highly appreciated. I prefer this sitation and will wait

**Comment by gsautter** [comment]
Was your idea, ultimately ... it's all an effect of the solution I cooked up when you asked for the GBIF dataset links to be added to the Zenodo depositions back in Geneva.
Treatment citation linking also uses that very mechanism, by the way, and I have a few more ideas what we can do with it.
