### ISSUE TITLE
figure wrong and does not show up   10.5281/zenodo.173577

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#59]
in this deposit, the figure does not show up

![image](https://user-images.githubusercontent.com/4609956/66897916-51835480-eff8-11e9-8ceb-a25c7ddd21a1.png)

https://doi.org/10.5281/zenodo.173577

5913FFCBFFF9FFE5FFE66702FF918359

**Comment by gsautter** [comment]
That figure looks like it's a completely white bitmap ... checking why it is that way ...

**Comment by gsautter** [comment]
Looking at the deposition number, though, it looks like this one is pretty old, one of our early-on  depositions.

**Comment by gsautter** [comment]
The most weird part is that the bitmap is OK in the IMF, and that one gets uploaded byte for byte as it is, without any modification. Hard t tell how this one broke almost 3 years ago.

**Comment by gsautter** [comment]
Turns out to be a weird collision of combined bitmap and graphics rendering in combination with some long-fixed graphics representation problem ... fixing the IMF now.

**Comment by gsautter** [comment]
Fixed ... replaced the figure with https://zenodo.org/record/3491926
