### ISSUE TITLE
website: Credit: arcadia

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#62]
We need to add on the front page(?) an acknowledgement of Arcadia, and probably also the collaboration with Zenodo/CERN.

**Comment by lyubomirpenev** [comment]
I propose the following formulation (hyperlinked organisations' names) :

A project of Plazi, Pensoft and Zenodo/CERN. Supported in part by the Arcadia Foundation

**Comment by myrmoteras** [comment]
ok with me

**Comment by teodorgeorgiev** [comment]
done

**Comment by myrmoteras** [comment]
@teodorgeorgiev thanks for fixing this. Might it be possible to hyperlink Arcadia with https://www.arcadiafund.org.uk/ and change the name from `Arcadida Foundation `to `Arcadia Fund` 
tx

**Comment by teodorgeorgiev** [comment]
sure!
