### ISSUE TITLE
adding treatments from FFCCFFDFFF9B8F1FFFD2714DFFBCFFEA to BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#68]
@gsautter can you please push the treatments from this articles to BLR and let me know. I would appreciate so I can finish a news article https://docs.google.com/document/d/101BKMInyCwxjCIijTjXBmXnfnU1iLX0XopsuWJ77j3M/edit

**Comment by gsautter** [comment]
Done ... the HTML issue I mentioned in the Skype wasn't at all an XSLT issue, but rather an effect of some weird XML nesting issues incurred by the markup of the treatment headings. In particular, `heading` and `emphasis` annotations were interleaved with the multiple `subSubSection`s marked in each of the headings. After correcting that markup, the HTMLs for BLR generated just fine.

**Comment by myrmoteras** [comment]
@gsautter is it an oversight that the taxonConceptLabel are not included, or is this because you still hammer out with Marcus how to construct them?

**Comment by gsautter** [comment]
Was indeed an oversight ... the example I had posted in https://github.com/plazi/arcadia-project/issues/97 was uploaded to the sandbox from my local machine, and I hadn't deployed the taxon concept labels yet. Done now, and the treatments are updated.
