### ISSUE TITLE
adding treatments from FFA6FFE8FF85CB7DB102C5500823306A to BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#69]
Hi Guido
sorry to interrupt again: Might it be possible to push the treatments from this article to BLR too. Marcus and I are writing letters to GBIF brazil to organize a meeting whilst we are in Brazil and it would be nice to have a Brazilian example to show
tx
Donat

**Comment by gsautter** [comment]
Sure, you got it, the treatments are up there now.

Had to fix a coordinate issue in one treatment, as the coordinates were given in UTM originally and the lat/long in the expected decimal degrees was manually added to the respective materials citation. In the latter process, degree signs were included in the lat/long attribute values, which the Zenodo custom metadata validation didn't like. After fixing that, the upload worked just fine.
