### ISSUE TITLE
taxonConceptLabel not correct

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#70]
in this https://zenodo.org/record/3610630#.XiDs7shKjAQ treatment, the taxonConceptLabel 
`openbiodiv:TaxonomicConceptLabel Parastacus buckupi Huber, 2018` should in fact include all the authors of the article: `Parastacus buckupi Huber, Ribeiro & Araujo, 2018`

**Comment by gsautter** [comment]
OK, that's exactly the kind of feedback I was asking ... how many authors would you like included? I'm rather sure listing some 10 or 20 authors is not really what we want, do we?

**Comment by myrmoteras** [comment]
Unfortunately, that’s how it is, unless authorities are explicitly listed, which is normally the case in multiauthored paper with many article authors

**Comment by gsautter** [comment]
Same behind the "sec."? Just making sure I don't produce any more _incorrect_ labels due to an incomplete spec.

**Comment by gsautter** [comment]
Updated accordingly now, to include all of the article authors, both before and after the "sec.", or any treatment authors explicitly given on original descriptions.
