### ISSUE TITLE
add treatments for 5364492BFF9C146C255A2423A079FFC2 to BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#71]
Hi Guido
might it be possible to add the treatments of this article to bLR? 5364492BFF9C146C255A2423A079FFC2
thanks

**Comment by gsautter** [comment]
Done: http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.zenodoDepId+doc.name+doc.articleUuid+doc.articleGbifId+doc.articleZenodoDepId+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+tax.name&groupingFields=doc.uuid+doc.zenodoDepId+doc.name+doc.articleUuid+doc.articleGbifId+doc.articleZenodoDepId+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+tax.name&FP-doc.articleUuid=5364492BFF9C146C255A2423A079FFC2&format=HTML
