### ISSUE TITLE
upload treatments to BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#75]
Hi Guido
Can you add these treatments that have been resulted from the training course today to BLR:
http://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.doi+doc.uploadUser+doc.uploadDate+cont.treatCount+cont.matCitCount+cont.figCountZen&groupingFields=doc.articleUuid+doc.doi+doc.uploadUser+cont.treatCount+cont.matCitCount+cont.figCountZen&limit=10&FP-doc.uploadDate=%222020-03-01%22&format=HTML
tx
donat

**Comment by gsautter** [comment]
Done ... obviously need a catch for URL related identifiers that come in from `bibRef`s without the "http://" or "https://" prefix ... Zenodo doesn't seem to like those.
