### ISSUE TITLE
multiple copies of the same treatment

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#76]
In this taxonomic treatment https://zenodo.org/record/3693224#.Xl50OKhKjAQ the treatment is multiple time in the description field

![image](https://user-images.githubusercontent.com/4609956/75789956-c61e1c00-5d6a-11ea-9e1e-fa6f06b91d56.png)

**Comment by gsautter** [comment]
Looks like pone of the minicourse people didn't get it all that right after all ... fixed now, deposition had to be replaced, is https://zenodo.org/record/3693228 now.
