### ISSUE TITLE
file does not upload FFAF832839254556323FB3179C51FFF1	

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#82]
@gsautter can you at some point check, why this file does not upload 

FFAF832839254556323FB3179C51FFF1

I can't figure out whether or what is wrong that does not allows uploading

**Comment by gsautter** [comment]
I just enqueued the UUID via the server console and followed the update ... towards the end, it gets an HTTP 504 error ("server internal error"), so I tend to think there's a problem on the Zenodo end of things right now ... should be a temporary thing ... I'll re-trigger the uploads soon as they fix it.

This affects all documents, so no need for further error reports about other missing documents.

**Comment by myrmoteras** [comment]
I think, Zenodo has troubles over the last weeks. I see on and off error messages, and it is difficult to get in touch with them
