### ISSUE TITLE
treatments not available: https://zenodo.org/record/3555661#.X3BYsmgzb8A

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#88]
@gsautter in this zookeys https://zookeys.pensoft.net/articles.php?id=35786&journal_name=zookeys with many treatments, there are not treaetments in BLR/TB?!
https://zookeys.pensoft.net/articles.php?id=35786&journal_name=zookeys
https://zenodo.org/record/3555661#.X3BYsmgzb8A

thanks for looking into this
d

**Comment by gsautter** [comment]
The article actually is in TB: http://tb.plazi.org/GgServer/summary/2691DADB7BA352BEBA377C901FC0AC97 , including some 137 treatments. How did you search for it to get no results?

**Comment by myrmoteras** [comment]
Via0 doi in blr

Today's new species: http://tb.plazi.org/GgServer/static/newToday.html

________________________________

**Comment by gsautter** [comment]
Could be this article hasn't been pushed to BLR just yet ... but it definitely is in TB.

**Comment by myrmoteras** [comment]
but it is still not in TB, and it is from 2019. @gsautter Can you push it?
