### ISSUE TITLE
taxonomicTreatment: html deposit issues: tokens without space

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#92]
@gsautter here is something that might have to do with the import and validation of the otherwise very nicely looking html in BLR for taxonomic treatments

![image](https://user-images.githubusercontent.com/4609956/103897777-526c3e80-50f4-11eb-8f35-4e29030ef13c.png)

The example is https://zenodo.org/record/4423106#.X_cAc9hKiPo   part of FFCFFFA7FF9BFF86DC51FFBFFFF1551D

**Comment by gsautter** [comment]
Fixed, general update is running ... should take a week, give or take, depending on the speed of Zenodo.

Was a pretty deep one, all the way down in the Java XSLT libraries, as well as our own XML handling facilities ... standalone whitespace is nothing in XML, especially between tags ... until it separates italics from bold face back to back in XHTML ...

Really hard to get XSLT to observe such standalone spaces ... took only 2 days, but at least now it looks good.
