### ISSUE TITLE
treatment issues: name combinations  D94BFFF8813AFFDE7016D56B781FFFE2	 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#94]
in this taxontreatment on BLR are the following issues: 

https://zenodo.org/record/4470008#.YBCSa-hKiPo

![image](https://user-images.githubusercontent.com/4609956/105912318-94214280-602b-11eb-92cd-faaf53fbd02f.png)

the names is wrong. Should be 

![image](https://user-images.githubusercontent.com/4609956/105912614-0b56d680-602c-11eb-9dcf-d8b349afd95c.png)

the taxonomic concept label should be

![image](https://user-images.githubusercontent.com/4609956/105912752-35a89400-602c-11eb-8e00-9da602a91dad.png)

Eumenes xanthura xanthura de Saussure, 1852 sec. Carpenter & Brown, 2021

**Comment by gsautter** [comment]
Just take a look at http://treatment.plazi.org/GgServer/xml/25728780812AFFCF7081D23C7C51FD83 ... the `species` and `subSpecies` attributes on the `taxonomicName` in the nomenclature section are missing ... nowhere for the Zenodo export to get them from, it ends up stuck with the genus.

The reason QC failed to catch this (most likely) is that the name failed to mark during the batch and was manually added later ... as visible from the version history of the treatment:
- batch result: http://treatment.plazi.org/GgServer/xml/25728780812AFFCF7081D23C7C51FD83/1
- current version: linked above

This is just a `taxonomicName` that needs fixing.

**Comment by mguidoti** [comment]
Thanks for figuring it out, @gsautter! 

Added to our pipeline, fix will be available tomorrow.

**Comment by diegojalvares** [comment]
Sorry guys, my error.

- I fix this treatment ([https://zenodo.org/record/4470008#.YBCrwehKjIX])
- I will re-check all treatments from this task
